# Generated by Django 4.2.9 on 2025-05-15 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.IntegerField(choices=[(0, 'Basic'), (1, 'Pro'), (2, 'Enterprise')], default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(help_text='Long description of the plan.', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional Phone number info from the user.', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Expired'), (2, 'Cancelled')], default=2)),
                ('start_date', models.DateField(help_text='Always populated when subscription starts.')),
                ('end_date', models.DateField(help_text='Always populated when subscription starts.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
