# Generated by Django 4.2.9 on 2025-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_plan_alter_customuser_phone_number_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9),
        ),
    ]
